import type { FoodItem, Order } from "./types"

export const FOOD_ITEMS: FoodItem[] = [
  {
    id: "1",
    name: "Margherita Pizza",
    category: "Pizza",
    description: "Classic pizza with tomato, mozzarella, and basil",
    price: 299,
    rating: 4.5,
    image: "/margherita-pizza.png",
  },
  {
    id: "2",
    name: "Pepperoni Pizza",
    category: "Pizza",
    description: "Delicious pizza topped with pepperoni and cheese",
    price: 349,
    rating: 4.7,
    image: "/pepperoni-pizza.png",
  },
  {
    id: "3",
    name: "Veggie Burger",
    category: "Burgers",
    description: "Fresh vegetable burger with special sauce",
    price: 199,
    rating: 4.2,
    image: "/veggie-burger.png",
  },
  {
    id: "4",
    name: "Chicken Burger",
    category: "Burgers",
    description: "Grilled chicken patty with lettuce and tomato",
    price: 249,
    rating: 4.6,
    image: "/delicious-chicken-burger.png",
  },
  {
    id: "5",
    name: "Caesar Salad",
    category: "Salads",
    description: "Crisp romaine lettuce with parmesan and croutons",
    price: 179,
    rating: 4.3,
    image: "/caesar-salad.png",
  },
  {
    id: "6",
    name: "Greek Salad",
    category: "Salads",
    description: "Fresh vegetables with feta cheese and olives",
    price: 189,
    rating: 4.4,
    image: "/greek-salad.png",
  },
  {
    id: "7",
    name: "Biryani",
    category: "Indian",
    description: "Fragrant rice with spiced meat and vegetables",
    price: 279,
    rating: 4.8,
    image: "/flavorful-biryani.png",
  },
  {
    id: "8",
    name: "Butter Chicken",
    category: "Indian",
    description: "Tender chicken in creamy tomato sauce",
    price: 299,
    rating: 4.7,
    image: "/butter-chicken.png",
  },
  {
    id: "9",
    name: "Pad Thai",
    category: "Asian",
    description: "Stir-fried noodles with shrimp and peanuts",
    price: 259,
    rating: 4.6,
    image: "/pad-thai.png",
  },
  {
    id: "10",
    name: "Sushi Roll",
    category: "Asian",
    description: "Fresh fish and vegetables wrapped in rice and seaweed",
    price: 329,
    rating: 4.9,
    image: "/sushi-roll.png",
  },
  {
    id: "11",
    name: "Tacos",
    category: "Mexican",
    description: "Soft tortillas with seasoned meat and toppings",
    price: 219,
    rating: 4.5,
    image: "/delicious-tacos.png",
  },
  {
    id: "12",
    name: "Burrito",
    category: "Mexican",
    description: "Large tortilla filled with beans, rice, and meat",
    price: 269,
    rating: 4.6,
    image: "/delicious-burrito.png",
  },
  {
    id: "13",
    name: "Chocolate Cake",
    category: "Desserts",
    description: "Rich and moist chocolate cake with frosting",
    price: 149,
    rating: 4.8,
    image: "/decadent-chocolate-cake.png",
  },
  {
    id: "14",
    name: "Ice Cream Sundae",
    category: "Desserts",
    description: "Vanilla ice cream with chocolate sauce and toppings",
    price: 129,
    rating: 4.7,
    image: "/ice-cream-sundae.png",
  },
  {
    id: "15",
    name: "Iced Coffee",
    category: "Beverages",
    description: "Cold brew coffee with ice and milk",
    price: 99,
    rating: 4.4,
    image: "/iced-coffee-refreshment.png",
  },
  {
    id: "16",
    name: "Fresh Juice",
    category: "Beverages",
    description: "Freshly squeezed orange juice",
    price: 89,
    rating: 4.5,
    image: "/fresh-juice.png",
  },
  {
    id: "17",
    name: "Falafel Wrap",
    category: "Wraps",
    description: "Crispy falafel with hummus and vegetables",
    price: 189,
    rating: 4.3,
    image: "/falafel-wrap.png",
  },
  {
    id: "18",
    name: "Chicken Shawarma",
    category: "Wraps",
    description: "Spiced chicken with tahini sauce in pita bread",
    price: 229,
    rating: 4.6,
    image: "/chicken-shawarma.jpg",
  },
  {
    id: "19",
    name: "Pasta Carbonara",
    category: "Pasta",
    description: "Creamy pasta with bacon and parmesan",
    price: 289,
    rating: 4.7,
    image: "/pasta-carbonara.png",
  },
  {
    id: "20",
    name: "Pasta Alfredo",
    category: "Pasta",
    description: "Fettuccine with creamy alfredo sauce",
    price: 279,
    rating: 4.6,
    image: "/pasta-alfredo.png",
  },
]

export const DUMMY_ORDERS: Order[] = [
  {
    id: "ORD001",
    items: [
      { ...FOOD_ITEMS[0], quantity: 2 },
      { ...FOOD_ITEMS[5], quantity: 1 },
    ],
    total: 787,
    status: "delivered",
    createdAt: "2025-10-15",
  },
  {
    id: "ORD002",
    items: [
      { ...FOOD_ITEMS[7], quantity: 1 },
      { ...FOOD_ITEMS[15], quantity: 2 },
    ],
    total: 487,
    status: "delivered",
    createdAt: "2025-10-18",
  },
]
